language: perl
install: export LDLOADLIBS=-lstdc++
script: 
    wget "https://bintray.com/lordofhyphens/Slic3r/download_file?file_path=boost_1_63_0-x64-gcc-4.9.2-linux-x64.tar.bz2" -o boost.tar.bz2
    tar -xjf boost.tar.bz2
    wget "https://bintray.com/lordofhyphens/Slic3r/download_file?file_path=slic3r-perl-dependencies-5.24.0-debian.tar.bz2" -o slic3r-deps.tar.bz2
    tar -xjf slic3r-deps.tar.bz2
    BOOST_DIR=`pwd`/boost_1_63_0 perl ./Build.PL
perl:
  - "5.24"
branches:
  only:
    - master
sudo: false
cache:
  apt: true
  directories:
    - local-lib
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - liblocal-lib-perl
    - g++-4.9
env: CC=g++-4.9
notifications:
  irc:
    channels:
      - "chat.freenode.net#slic3r"
    on_success: change
    on_failure: always
    use_notice: true
