language: perl
perl:
  - "5.14"
  - "5.18"
  - "5.20"

install:
  # LDLOADLIBS hack to fix ExtUtils::CppGuess compilation (-lstdc++ needs to be
  # placed after CppGuessTest.o)
  - LDLOADLIBS=-lstdc++ cpanm --installdeps --verbose . || true

script: perl ./Build.PL

branches:
  only:
    - master
    - stable

sudo: false
cache:
    - apt

addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
